/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include"led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint8_t arr[] = {LED_GREEN, LED_ORANGE, LED_RED, LED_BLUE};
	for(uint8_t i = 0 ; i < 4 ; i++)
		led_init(arr[i]);

	uint8_t i = 0;
	while(1)
	{
		led_toggle(arr[i]);
		DelayMs(500);
		i = (i + 1) % 4;
	}
}

/*
int main(void)
{
	uint8_t arr[] = {LED_GREEN, LED_ORANGE, LED_RED, LED_BLUE};
	for(uint8_t i = 0 ; i < 4 ; i++)
		led_init(arr[i]);

	while(1)
	{
		for(uint8_t i = 0 ; i < 4 ; i++)
		{
			led_toggle(arr[i]);
			DelayMs(1000);
		}
	}
}
*/
/*
int main(void)
{
	uint8_t arr[] = {LED_GREEN, LED_ORANGE, LED_RED, LED_BLUE};
	for(uint8_t i = 0 ; i < 4 ; i++)
		led_init(arr[i]);

	for(uint8_t i = 0 ; i < 4 ; i++){
		led_on(arr[i]);
		DelayMs(2000);
	}

	for(uint8_t i = 0 ; i < 4 ; i++){
		led_off(arr[i]);
		DelayMs(2000);
	}

	while(1);
}
*/
/*
int main(void)
{
	uint8_t arr[] = {LED_GREEN, LED_ORANGE, LED_RED, LED_BLUE};
	for(uint8_t i = 0 ; i < 4 ; i++)
		led_init(arr[i]);

	for(uint8_t i = 0 ; i < 4 ; i++){
		led_on(arr[i]);
		DelayMs(2000);
	}

	while(1);
}
*/
/*
int main(void)
{
	uint8_t arr[] = {LED_GREEN, LED_ORANGE, LED_RED, LED_BLUE};
	for(uint8_t i = 0 ; i < 4 ; i++)
		led_init(arr[i]);

	while(1)
	{
		for(uint8_t i = 0 ; i < 4 ; i++)
			led_toggle(arr[i]);
		DelayMs(2000);
	}
}
*/

/*
int main(void)
{
	led_init(LED_GREEN);

	while(1)
	{
		led_toggle(LED_GREEN);
		DelayMs(2000);
	}
}
*/
