/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "uart.h"
#include "rtc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

static char str[50];
int main(void)
{
	RtcDate_t dt = { .date = 31, .month = 12, .year = 24, .weekday = 2 };
	RtcTime_t tm = { .hr = 23, .min = 59, .sec = 55 };
	UartInit(9600);
	UartPuts("RTC Demo for DESD\r\n");
	RtcInit(&dt, &tm);
	while(1) {
		RtcGetTime(&tm);
		RtcGetDate(&dt);
		sprintf(str, "%02d-%02d-%02d (%d) %02d:%02d:%02d\r\n", dt.date, dt.month, dt.year, dt.weekday,
									tm.hr, tm.min, tm.sec);
		UartPuts(str);
		DelayMs(1000);
	}
}


