/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include<FreeRTOS.h>
#include<FreeRTOSConfig.h>
#include<task.h>
#include<led.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void vAperiodicTask(void *pvParam)
{
	uint16_t pin = (uint16_t)pvParam;
	while(1)
	{
		led_toggle(pin);
		vTaskDelay(1000 / portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}

void vPeriodicTask(void *pvParam)
{
	uint16_t pin = (uint16_t)pvParam;
	portTickType xPreviousWakeupTime = xTaskGetTickCount();
	while(1)
	{
		led_toggle(pin);
		vTaskDelayUntil(&xPreviousWakeupTime , 2000 / portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}



int main(void)
{
	led_init(LED_GREEN);
	led_init(LED_RED);

	xTaskCreate(vPeriodicTask, "Task1", configMINIMAL_STACK_SIZE, (void *)LED_GREEN, 4, NULL);
	xTaskCreate(vAperiodicTask, "Task2", configMINIMAL_STACK_SIZE, (void *)LED_RED, 3, NULL);

	vTaskStartScheduler();

	while(1);
}

